### PR TITLE
Update dependencies and example

### PR DESCRIPTION
**Pull request by joebochill**
#### Changes proposed in this Pull Request:
- Update the dependencies used and required by the workflow
- Re-scaffold the demo using the CLI template
- Make sure everything works

### CODE REVIEW

**Review by emclaug2 — APPROVED** [review]

**Comment by joebochill** [comment]
@emclaug2  Did you clone this down and run it to make sure everything is in order?

**Review by daileytj — APPROVED** [review]
Looks good. Can you update the changelog to remove the "(Not Published Yet)"?

**Review by daileytj — CHANGES_REQUESTED** [review]
Actually, having some issues locally... 

Going to do a fresh clone to verify.

**Comment by emclaug2** [comment]
I uninstalled the app on the emulator & then ran some issues reinstalling the app; I'm going to join Tom and do a fresh clone again.

**Comment by jeffvg** [comment]
all looks good. Just this warning on android....

If you want to use Reanimated 2 then go through our installation steps https://docs.swmansion.com/react-native-reanimated/docs/installation 
App@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.example&modulesOnly=false&runModule=true:100172:36
RCTView
View

**Review by daileytj — APPROVED** [review]
Ok... working fine locally now.

**Comment by joebochill** [comment]
Alright, I'm going to drop the dependency for react-native-reanimated back down to 1.x to fix the issue on android.

**Pull request merged**
