### PR TITLE
Feature/2518 blui rebrand

### PR DESCRIPTION
**Pull request by daileytj**
Fixes PXBLUE-2518.

#### Changes proposed in this Pull Request:
- Rebrand latest to Brightlayer UI

### CODE REVIEW

**Comment by daileytj** [comment]
I still need to fix some tests, but could use some eyes on the core of this.

**Comment by daileytj** [comment]
I still need to fix some tests, but could use some eyes on the core of this.

**Comment by huayunh** [comment]
- [ ] link to pictures in login-workflow/README.md

**Comment by daileytj** [comment]
> * [ ]  link to pictures in login-workflow/README.md

I'm holding off on anything that requires a reference to brightlayer-ui github since it doesn't exist yet. This will take some finesse and back and forth. There's some stuff that just won't be able to be fixed until we switch the org name. We'll need to update the submodule pointer at some point as well.

**Comment by jeffvg** [comment]
everything looks good to me. Are we coming back after this to update sub-module and old @pxblue/react-native-auth-workflow dependency

**Comment by daileytj** [comment]
@jeffvg Yeah, the submodule pointer will need to be updated after the org name change and the @pxblue dependencies remaining will be removed from the demo as soon as we have this package published

**Review by jeffvg — APPROVED** [review]

**Review by emclaug2 — APPROVED** [review]
Let's publish a beta!

**Pull request merged**
