### PR TITLE
Add the custom registration examples back

### PR DESCRIPTION
**Pull request by joebochill**
#### Changes proposed in this Pull Request:
- Add the custom registration field examples back into the demo

### CODE REVIEW

**Comment by jeffvg** [comment]
must be missing more...

**Comment by huayunh** [comment]
@jeffvg Can you re-upload the image?

**Comment by jeffvg** [comment]
> @jeffvg Can you re-upload the image?

image

**Comment by joebochill** [comment]
That will be resolved when it merges with the other PR that does the language updates

**Review by jeffvg — APPROVED** [review]

**Pull request merged**
