### PR TITLE
Upgrade react-native to fix iOS images not loading bug

### LINKED ISSUE #32: iOS example app images not loading (iOS 14.1 Xcode 12)
When running the example app on an iOS simulator (iPhone 12 - iOS 14) in Xcode 12, the main logo does not appear to load.

Screen Shot 2020-11-10 at 4 03 27 PM

Here are related issues in the react-native repo:

https://github.com/facebook/react-native/issues/29369
https://github.com/facebook/react-native/issues/29279 - one line fix in pod dependency to build locally fine
https://github.com/facebook/react-native/issues/29237

Appears to be fixed in v0.63.2 https://github.com/react-native-community/releases/blob/master/CHANGELOG.md#v0632

### PR DESCRIPTION
**Pull request by daileytj**
Fixes #32.

#### Changes proposed in this Pull Request:
- Upgrade to react-native@0.63.3

note: React Native 0.63 no longer supports iOS 9

### CODE REVIEW

**Comment by huayunh** [comment]
Do we want to make an effort to upgrade our entire RN library to 63? Can you make a backlog story on this?

**Comment by emclaug2** [comment]
@jeffvg Can you test out the login-workflow on an android device? 

Whenever I try to run the example, the app installs on the emulator but it fails to open for me.

**Comment by jeffvg** [comment]
> @jeffvg Can you test out the login-workflow on an android device?
> 
> Whenever I try to run the example, the app installs on the emulator but it fails to open for me.

looking now. Does iOS need pods updated locally or does the project

**Comment by jeffvg** [comment]
I have the same results as @emclaug2 on android

Unable to strip library '/pxblue/react-native-workflows/login-workflow/example/android/app/build/intermediates/merged_native_libs/debug/out/lib/armeabi-v7a/libhermes-executor-debug.so' due to missing strip tool for ABI 'ARMEABI_V7A'

**Comment by daileytj** [comment]
Screen Shot 2020-11-24 at 12 38 30 PM
Works on my machine... ¯\_(ツ)_/¯

**Comment by jeffvg** [comment]
> Screen Shot 2020-11-24 at 12 38 30 PM
> Works on my machine... ¯_(ツ)_/¯

did you install xCode 12.2

**Comment by joebochill** [comment]
This is stepping on some of the same things I was stepping on for the RNP v4 update. Let's hold off on merging any of these until we see if a new scaffold helps alleviate some of those weird issues that cropped up.

**Comment by joebochill** [comment]
Made some fixes ion #35. That PR should cover this now (plus some additional package updates).

**Pull request closed without merging**
