### PR TITLE
Update login workflow and demo to use RNP 4

### PR DESCRIPTION
**Pull request by joebochill**
For PXBLUE-XXXX.

#### Changes proposed in this Pull Request:
- Update login workflow to use RNP 4
- Update Theme type throughout
- Update example project to use RNP4 too

### CODE REVIEW

**Comment by huayunh** [comment]
I saw plenty of ts ignore in the `/src` folder that says

```
@ts-ignore waiting for 4.0.0 of react-native-paper to fix these typings
```

**Review by huayunh — COMMENTED** [review]
Code looks good. Haven't spinned anything up locally yet.

**Comment by joebochill** [comment]
> I saw plenty of ts ignore in the `/src` folder that says
> 
> ```
> @ts-ignore waiting for 4.0.0 of react-native-paper to fix these typings
> ```

Good catch, I forgot to clean those up.

**Comment by joebochill** [comment]
I made a new branch (feature/remove-ts-ignore) that removes those comments. The start command will throw some type warnings while it's spinning up, but it runs successfully. To make those go away, I think we need to update the typescript version in the example project (tried to do it, but it opened up another can of worms). If you're okay with the warnings for now until we rescaffold that example (using swift!), then you can make a PR from the other branch instead.

**Comment by jeffvg** [comment]
everything seems to run fine on both iOS and Android, just the error at start. Also it might be my system since I installed latest xCode but on iPhone running 14.2 we are missing some styling....

example/App.tsx:36:13 - error TS2322: Type '{ children: Element; authActions: AuthUIActionsFunction; registrationActions: () => RegistrationUIActions; showSelfRegistration: true; ... 4 more ...; contactPhoneLink: string; }' is not assignable to type 'IntrinsicAttributes & AuthUIContextProviderProps & { children?: ReactNode; }'.
  Property 'contactPhoneLink' does not exist on type 'IntrinsicAttributes & AuthUIContextProviderProps & { children?: ReactNode; }'.

36             contactPhoneLink={'1-800-123-4567'}
               ~~~~~~~~~~~~~~~~

src/screens/ContactSupport.tsx:98:43 - error TS2339: Property 'contactPhoneLink' does not exist on type 'ContactParams'.

98     const contactPhoneLink = routeParams?.contactPhoneLink ?? '';
                                             ~~~~~~~~~~~~~~~~

src/screens/PreAuthContainer.tsx:81:53 - error TS2339: Property 'contactPhoneLink' does not exist on type 'AuthUIContextProviderProps'.

81                         contactPhoneLink: authProps.contactPhoneLink ?? '1-888-EXA-TEST',
                                                       ~~~~~~~~~~~~~~~~


Found 3 errors.

**Comment by huayunh** [comment]
> If you're okay with the warnings for now until we rescaffold that example (using swift!), then you can make a PR from the other branch instead.

Swift? 🤣 

Yeah, I see what you mean here. I am a bit hesitant. I am more inclined to leave them there but change the comment content to something else, for example, "todo: update typescript to 4.x to fix those typings" so that they are less misleading to our users, and make a separate story in the backlog to investigate in this.

**Comment by joebochill** [comment]
> everything seems to run fine on both iOS and Android, just the error at start. Also it might be my system since I installed latest xCode but on iPhone running 14.2 i'm missing some stuff....pic below

The missing images is already logged in the bug that shiverware reported (we groomed it on Wednesday).

**Comment by jeffvg** [comment]
Having issues getting Android example running for some reason. App deploy flashes on screen then goes away. Anyone having issues with this?
Also the iOS example throws terminal warning to run "pod update Folly --no-repo-update" I've had to do this before and it worked but I can't right now because I don't have a pod file yet

**Comment by joebochill** [comment]
closing in favor of #35

**Comment by joebochill** [comment]
> Having issues getting Android example running for some reason. App deploy flashes on screen then goes away. Anyone having issues with this?
> Also the iOS example throws terminal warning to run "pod update Folly --no-repo-update" I've had to do this before and it worked but I can't right now because I don't have a pod file yet

Make sure you are on the latest version of cocoapods. What do you mean you don't have a Podfile? Try out the other branch (#35) that has a few more updates as well. I don't have any issues with Android there. You may want to delete any existing apps on your simulator before running it (it has a generic name of example, which may conflict with some previous installations).

**Pull request closed without merging**
