### PR TITLE
Release 3.2.1

### PR DESCRIPTION
**Pull request by joebochill**
#### Changes proposed in this Pull Request:
- Fixes issue with the EULA not displaying in new projects

### CODE REVIEW

**Comment by jeffvg** [comment]
ran through all the screens on android and the last one was self-invite. App was back to login screen and for no reason got this..can someone verify on android

image

**Comment by joebochill** [comment]
I will take a run through on both platforms with a fresh clone now

**Comment by joebochill** [comment]
I've seen that pop up on occasion when refreshing / relinking

**Comment by jeffvg** [comment]
for me it's just really running slow but now I see this on android..

image

**Comment by joebochill** [comment]
I just ran through all the screens for the demo on Android and iOS and didn't have any issues. Android ran a touch slow (as it usually does), but I also have a bunch of stuff running on my machine ATM.

**Comment by jeffvg** [comment]
> I just ran through all the screens for the demo on Android and iOS and didn't have any issues. Android ran a touch slow (as it usually does), but I also have a bunch of stuff running on my machine ATM.

yeah, I rebooted and it seems ok now.

**Review by jeffvg — APPROVED** [review]

**Review by daileytj — APPROVED** [review]

**Pull request merged**
