### PR TITLE
Merge latest changes into master

### PR DESCRIPTION
**Pull request by joebochill**
#### Changes proposed in this Pull Request:
- Merge the latest updates into master

> published as @pxblue/react-native-auth-workflow@1.3.0

### CODE REVIEW

**Review by emclaug2 — APPROVED** [review]

**Comment by jeffvg** [comment]
I'm getting 5 errors running yarn start:example-android and yarn start:example-ios on fresh clone. Both are running....

- example/App.tsx:11:8 - error TS2307: Cannot find module '@pxblue/react-native-auth-workflow' or its corresponding type declarations.
11 } from '@pxblue/react-native-auth-workflow';

- example/App.tsx:20:28 - error TS2307: Cannot find module '@pxblue/react-native-themes' or its corresponding type declarations.
20 import * as PXBThemes from '@pxblue/react-native-themes';

- example/src/actions/AuthUIActions.tsx:2:55 - error TS2307: Cannot find module '@pxblue/react-native-auth-workflow' or its corresponding type declarations.
2 import { AuthUIActions, SecurityContextActions } from '@pxblue/react-native-auth-workflow';

- example/src/actions/RegistrationUIActions.tsx:2:65 - error TS2307: Cannot find module '@pxblue/react-native-auth-workflow' or its corresponding type declarations.
2 import { RegistrationUIActions, AccountDetailInformation } from '@pxblue/react-native-auth-workflow';

- example/src/screens/ExampleHome.tsx:3:54 - error TS2307: Cannot find module '@pxblue/react-native-auth-workflow' or its corresponding type declarations.
3 import { useSecurityActions, useSecurityState } from '@pxblue/react-native-auth-workflow';

**Comment by joebochill** [comment]
> I'm getting 5 errors running yarn start:example-android and yarn start:example-ios on fresh clone. Both are running....
> 
> * example/App.tsx:11:8 - error TS2307: Cannot find module '@pxblue/react-native-auth-workflow' or its corresponding type declarations.
>   11 } from '@pxblue/react-native-auth-workflow';
> * example/App.tsx:20:28 - error TS2307: Cannot find module '@pxblue/react-native-themes' or its corresponding type declarations.
>   20 import * as PXBThemes from '@pxblue/react-native-themes';
> * example/src/actions/AuthUIActions.tsx:2:55 - error TS2307: Cannot find module '@pxblue/react-native-auth-workflow' or its corresponding type declarations.
>   2 import { AuthUIActions, SecurityContextActions } from '@pxblue/react-native-auth-workflow';
> * example/src/actions/RegistrationUIActions.tsx:2:65 - error TS2307: Cannot find module '@pxblue/react-native-auth-workflow' or its corresponding type declarations.
>   2 import { RegistrationUIActions, AccountDetailInformation } from '@pxblue/react-native-auth-workflow';
> * example/src/screens/ExampleHome.tsx:3:54 - error TS2307: Cannot find module '@pxblue/react-native-auth-workflow' or its corresponding type declarations.
>   3 import { useSecurityActions, useSecurityState } from '@pxblue/react-native-auth-workflow';

Those types should be fixed in the current version of the auth workflow (the one we're about to release). When we first install the latest version from npm 1.2.1, they aren't there, but after the linking script moves the latest files in, they're there and the demo will run successfully. 

I can go in and bump the initial installed version in the demo once I publish this new version and i'll include that in this PR to make sure it removes those console warnings.

**Comment by joebochill** [comment]
Welp, I lied. Apparently that did not fix it — I'll take a little bit of a deeper look into it.

**Comment by joebochill** [comment]
Should be fixed now...we were doing a build step before the dependencies were installed for the example project. I reordered this so that we install all of the dependencies first before doing the `bob build`

**Review by jeffvg — APPROVED** [review]
that worked, looks good

**Pull request merged**
