### PR TITLE
Publish 2.0.0

### PR DESCRIPTION
**Pull request by joebochill**
Moves the latest published code from @pxblue/react-native-auth-workflow@2.0.0 into master branch

#### Changes proposed in this Pull Request:
- Upgrade dependencies
- Use RNP version 4

### CODE REVIEW

**Comment by jeffvg** [comment]
looks good on android.

**Comment by huayunh** [comment]
When I first `yarn start:example-ios`, Cocoapod yelled at me to `pod update Folly --no-repo-update`.

So I ran that command in the /ios folder, Podfile.lock updated itself, and try starting the example again. This time I got this text chunk in my VSC console (not the system console with the big react-native logo on it):
```
...
$ react-native run-ios
info Found Xcode workspace "example.xcworkspace"
info Building (using "xcodebuild -workspace example.xcworkspace -configuration Debug -scheme example -destination id=C7EAA1A2-D64B-4AEB-8B8D-630E949608C4")
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening example.xcworkspace. Run CLI with --verbose flag for more details.
note: Using new build system
note: Planning build
note: Using build description from disk
Build system information
error: unable to attach DB: error: accessing build database "/Users/c3050144/Library/Developer/Xcode/DerivedData/example-dyxfoowucihgnrfafuzrnzbfdhzx/Build/Intermediates.noindex/XCBuildData/build.db": database is locked Possibly there are two concurrent builds running in the same filesystem location.

warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 6.0, but the range of supported deployment target versions is 8.0 to 13.2.99. (in target 'OpenSSL-Universal' from project 'Pods')
warning: Capabilities for Signing & Capabilities may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the example editor. (in target 'example' from project 'example')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 8.0 to 13.2.99. (in target 'react-native-viewpager' from project 'Pods')
warning: no rule to process file '/Users/c3050144/Documents/pxblue/react-native-workflows/login-workflow/example/ios/Pods/Flipper-RSocket/rsocket/README.md' of type 'net.daringfireball.markdown' for architecture 'x86_64' (in target 'Flipper-RSocket' from project 'Pods')
warning: no rule to process file '/Users/c3050144/Documents/pxblue/react-native-workflows/login-workflow/example/ios/Pods/Flipper-RSocket/rsocket/benchmarks/CMakeLists.txt' of type 'text' for architecture 'x86_64' (in target 'Flipper-RSocket' from project 'Pods')
warning: no rule to process file '/Users/c3050144/Documents/pxblue/react-native-workflows/login-workflow/example/ios/Pods/Flipper-RSocket/rsocket/benchmarks/README.md' of type 'net.daringfireball.markdown' for architecture 'x86_64' (in target 'Flipper-RSocket' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 5.0, but the range of supported deployment target versions is 8.0 to 13.2.99. (in target 'CocoaAsyncSocket' from project 'Pods')

** BUILD FAILED **


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

But the iOS project spins itself with no problem. 

Noticed a few design problems; I am going to log them as issues here.

**Comment by joebochill** [comment]
@huayunh do you have the latest version of cocoapods and xCode installed?

**Comment by joebochill** [comment]
There are a couple of design issues already logged, just make sure anything you're logging is not already accounted for.

**Comment by huayunh** [comment]
My xcode is on 11.3... should I still intentionally stay on a lower version?
Cocoapods vesion is the same as yours.

**Review by emclaug2 — APPROVED** [review]

**Comment by joebochill** [comment]
> My xcode is on 11.3... should I still intentionally stay on a lower version?
> Cocoapods vesion is the same as yours.

If you are on 12.3 I would not drop down

**Comment by joebochill** [comment]
I've run into those pod warnings semi-regularly when updating various repos. I suspect that it is an issue downstream in one of our dependencies (because we don't actually specify deployment target for any of our pods as far as I can tell). Might be something we just need to sit on until they update (or potentially we can add the postinstall script from the following thread, though I'm not sure if we want to arbitrarily set the deployment version for everything without knowing how it might affect those pods). If it's still running fine, I would probably not worry about it for now.

https://developer.apple.com/forums/thread/656616#:~:text=IPHONEOS_DEPLOYMENT_TARGET%20is%20set%20to%208.0,versions%20is%209.0%20to%2014.0.

**Review by huayunh — APPROVED** [review]

**Pull request merged**
