### PR TITLE
Publish 1.1.0 with latest shiverware changes, Publish 1.2.1 with split logic package

### PR DESCRIPTION
**Pull request by joebochill**
#### Changes proposed in this Pull Request:
- Published as @pxblue/react-native-auth-workflow@1.1.0
- Published as @pxblue/react-native-auth-workflows@1.2.1
    - @pxblue/react-auth-shared@1.0.1 is also published

### CODE REVIEW

**Comment by jeffvg** [comment]
latest is getting installed but should the actual versions in package reflect the new one
"@pxblue/colors": "^2.0.0",
        "@pxblue/eslint-config": "^1.1.5",
        "@pxblue/prettier-config": "^1.0.2"

Just noticed pxblue/colors is listed in peer-dependencies and dev

**Comment by joebochill** [comment]
> latest is getting installed but should the actual versions in package reflect the new one
> "@pxblue/colors": "^2.0.0",
> "@pxblue/eslint-config": "^1.1.5",
> "@pxblue/prettier-config": "^1.0.2"
> 
> Just noticed pxblue/colors is listed in peer-dependencies and dev

The lint config should be updated to 2.0.0, but that's a breaking change...we should log that as an enhancement since there will be some refactoring required with the new rules.

Usually anything we have listed as a peerDependency will also need to be a dev dependency (peerDependencies are not installed with a yarn install, and if we need the packages during development/testing, then we have to have them in devDependencies too).

**Comment by joebochill** [comment]
Added another PR #20 into dev branch. Wait for that to be merged before merging this one.

**Comment by joebochill** [comment]
> Spins nicely on my iOS simulator. Would like to have our updated form validation specifications incorporated in the future.

Let's log an enhancement 👍

**Pull request merged**
