### PR TITLE
Port RN specific elements from shared auth

### PR DESCRIPTION
**Pull request by joebochill**
#### Changes proposed in this Pull Request:
- Move DismissKeyboardView and i18n object from the shared auth repository

NOTE: Need to update the dependency from beta once the shared auth PR is merged and a full version is published

### CODE REVIEW

**Comment by jeffvg** [comment]
seeing this in this branch..

image

also looks like the dev branch has hard coded email?

image

**Comment by joebochill** [comment]
@jeffvg That error was being caused because the version of RNAWin the package.json file for the example is the latest one available. This version has a dependency on the older version of the react-auth-shared, so the only way to make that work out of the box would be to either add RAS as a dependency for the demo (not desirable because it should come from RNAW) or publish a new version of this package with the updates to the dependency (can't publish this yet because we are still reviewing it 😄  ). Instead, I hooked up the RAS as a git submodule (we wanted to do this anyway) and linked it into the node module folder of the example. It works exactly like the React one that I'm working on now does. It will now use the latest code for RNAW and RAS simultaneously.

**Comment by joebochill** [comment]
@jeffvg The hardcoded credentials is because you have the "remember me" checkbox checked. That is the last email address you used to sign in.

**Comment by jeffvg** [comment]
> @jeffvg The hardcoded credentials is because you have the "remember me" checkbox checked. That is the last email address you used to sign in.

must be my great cache feature that haunts my PC

**Pull request merged**
