### PR TITLE
Initial upgrade for security issues

### PR DESCRIPTION
**Pull request by jeffvg**
#### Changes proposed in this Pull Request:
- React-native-workflows\login-workflow (_has deep linking issue with login_ )
- 6460 vulnerabilities found
- Severity: 6458 Low | 2 High

After upgrade
- 5 vulnerabilities found
- Severity: 4 Low | 1 High

- React-native-workflows\example
- 14936 vulnerabilities found
- Severity: 14935 Low | 1 High

After upgrade
- 5 vulnerabilities found
- Severity: 4 Low | 1 High

### CODE REVIEW

**Comment by jeffvg** [comment]
@joebochill can you help out with this build error in deep linking

**Comment by jeffvg** [comment]
After upgrading react-native-vector-icons to "7.0.0" on example, noticed the check-box not displaying but is selectable 

image

**Comment by jeffvg** [comment]
Project loads up on iOS, both create account and invite register are broke in the safe area view. Note: seems the checkbox is displaying for iOS (remember me) where android in not. Android project loads and runs, just missing the checkbox icons for remember me and EULA page

**Comment by joebochill** [comment]
@jeffvg  this has been open for a while. Are we planning do further work on this to get it to work, or should we close it and revisit it later?

**Comment by jeffvg** [comment]
> @jeffvg this has been open for a while. Are we planning do further work on this to get it to work, or should we close it and revisit it later?

Yes I'm going to close it for now. We have a story on BL to revisit this

**Pull request closed without merging**
