### PR TITLE
Make the auth workflow work with a dark theme

### LINKED ISSUE #67: Bottom buttons are too close to the bottom
## Describe the desired behavior

I put shadow here just to highlight the positioning. In the actual design there is no shadow there.
image

For reference, this is what the button positioning looks like
image
(16px padding around this 36px tall button)

## Describe the current behavior

image

### LINKED ISSUE #70: Password error shows for network errors on login
#### Describe the bug
The username and password fields show 'incorrect username or password' message regardless of what network error is reported (even if the error is not because of the username or password).

#### What is the expected behavior?
This error message should only be shown if the error thrown is due to the username/password.

#### What are the steps to reproduce?
1. Open the demo project
2. Configure the login action to throw an error
2. Attempt to log in
3. Observe that the error message is displayed below the inputs.
		
#### Anything else to add?
This is reported by the CRDS-RWD team. 

We should be able to key off of the error message that is thrown to determine whether to show this error message or not.

### PR DESCRIPTION
**Pull request by joebochill**
For PXBLUE-1945 .
Fixes #67 
Fixes #70 

#### Changes proposed in this Pull Request:
- Add a new context provider `AltThemeProvider`
- Add wrapper components for RNP components that need to use the alt theme
- Clean up inline styles
- Swap in the MobileStepper component
- Fix bug with button alignment
- Fix bug with error message
- Update the docs

There are a couple of places where I had to set color values or styles inline/via props (e.g. Header background colors) as a workaround to some bugs that I found on components. I logged new issues for them.

#### Screenshots:
image

### CODE REVIEW

**Comment by huayunh** [comment]
Saw this in the console:  
```
 LOG  Running "example" with {"rootTag":1,"initialProps":{}}
 WARN  RCTBridge required dispatch_sync to load RCTDevLoadingView. This may lead to deadlocks
```

**Comment by huayunh** [comment]
image

**Comment by huayunh** [comment]
Color of those checkboxes
image

**Comment by huayunh** [comment]
Debug mode -> Test invitation -> load EULA, I expect a dark loading screen instead of a spinner with a white flash
image

**Comment by huayunh** [comment]
I expect the app bar and the wavy thing to be more connected without a shadow crossing through. This would be an exception to the default dark theme color in that the header would stay blue (maybe put this in darkblue alt?)

In general dark theme app bar shall stay dark, although I've seen Eric using some blue app bars in his applications.

image

**Comment by joebochill** [comment]
> Saw this in the console:
> 
> ```
>  LOG  Running "example" with {"rootTag":1,"initialProps":{}}
>  WARN  RCTBridge required dispatch_sync to load RCTDevLoadingView. This may lead to deadlocks
> ```

This has popped up occasionally in a couple of the react native projects since updating the RN version. I suspect it will eventually clear itself up in a future patch.

**Comment by joebochill** [comment]
> UserMenu icon colors are wrong

Bug logged for this on the component library (https://github.com/pxblue/react-native-component-library/issues/154). I'll use the iconColor prop as a workaround for now.

**Comment by joebochill** [comment]
> I expect the app bar and the wavy thing to be more connected without a shadow crossing through. You have this correct in the account registration success screen though.
> 
> This would be an exception to the default dark theme color in that the header would stay blue (maybe put this in darkblue alt?) In general dark theme app bar shall stay dark, although I've seen Eric using some blue app bars in his applications.
> 
> image

Logged an issue on the Header component for the incorrect default behavior: https://github.com/pxblue/react-native-component-library/issues/155

I'll override these with props for the time being.

**Comment by joebochill** [comment]
Having some issues with Headers and button alignment now...looking into it

**Comment by huayunh** [comment]
I saw this in the console output

```
$ bob build
ℹ Building target commonjs
ℹ Cleaning up previous build at lib/commonjs
ℹ Compiling 66 files in src with babel
✓ Wrote files to lib/commonjs
ℹ Building target module
ℹ Cleaning up previous build at lib/module
ℹ Compiling 66 files in src with babel
✓ Wrote files to lib/module
ℹ Building target typescript
ℹ Cleaning up previous build at lib/typescript
ℹ Generating type definitions with tsc
example/src/components/TextInput.tsx:6:10 - error TS2305: Module '"@pxblue/react-native-auth-workflow"' has no exported member 'ThemedTextInput'.

6 import { ThemedTextInput } from '@pxblue/react-native-auth-workflow';
           ~~~~~~~~~~~~~~~
```

**Comment by huayunh** [comment]
When you click "logout" in dark mode, there is a flash of white.

**Comment by huayunh** [comment]
Dark theme looks good to me otherwise (didn't test on android, still need to properly set things up)

**Comment by joebochill** [comment]
> 6 import { ThemedTextInput } from '@pxblue/react-native-auth-workflow';
>            ~~~~~~~~~~~~~~~
> ```

The example is using beta.0 by default (which was a version before I exported the themed component wrappers). Once the link:workflows command is run (or yarn start:example) they will be there. I'll make another beta and update the example too.

**Review by daileytj — APPROVED** [review]

**Pull request merged**
