### PR TITLE
Update packages to ~latest

### PR DESCRIPTION
**Pull request by joebochill**
Update lots of packages to latest (typescript, react native, components, react native paper)

#### Changes proposed in this Pull Request:
- Updates packages
- Re-lint

> **NOTE**: There is an issue in the ViewPager component that is causing problems (opening the deep link debug link for invite register will crash the app). This PR downgrades the dependency to 3.x to fix that error, but I don't think that is a good solution long term since we were previously depending on version 4.x.

### CODE REVIEW

**Comment by joebochill** [comment]
I narrowed to bug down to a specific version of react-native-viewpager. I put us back on 4.0.1 (the last working version) and updated the readme instructions to include that specific version.

Everything should be working smoothly now.

For reference: https://github.com/callstack/react-native-viewpager/issues/167

**Comment by jeffvg** [comment]
looks like the EULA checkbox is missing in action again on android.

image

**Comment by joebochill** [comment]
> looks like the EULA checkbox is missing in action again on android.
> 
> image

Is it missing in dev?

**Comment by joebochill** [comment]
> looks like the EULA checkbox is missing in action again on android.

Is it missing in dev?

**Comment by joebochill** [comment]
> > looks like the EULA checkbox is missing in action again on android.
> 
> Is it missing in dev?

No it's not. I think something may have changed in RNVI from v6 to 7. There was a step in their setup instructions that we were missing on the Android side. For some reason the Material icons were working fine, but the Material Community ones are not (I guess the Android platform has material icons by default). Anyway, I added that extra config line in the gradle file and it looks like the checkboxes are working correctly now.

**Review by jeffvg — APPROVED** [review]
no issues identified looks good on android and iOS

**Pull request merged**
